### ISSUE TITLE
Any recommendation for support obs and actions spaces in Dict?

### ISSUE THREAD

**Issue by heng2j** [proroklab/HetGPPO#1]
Hi @matteobettini,

Thank you for the wonderful work on HetGPPO and VMAS! I am using HetGPPO on my custom Blue team vs Red team competitive env, which uses gym.spaces. Dict as observation_space and action_space. I mapped the obs and actions by agent_id with the policy mapping function described in this official RLlib example [multi_agent_different_spaces_for_agents.py](https://github.com/ray-project/ray/blob/ray-2.2.0/rllib/examples/multi_agent_different_spaces_for_agents.py) to set up heterogeneous spaces for my agents. 

I noticed that VMAS uses tuples for the spaces, and so as GPPO. Any recommendations for preciously mapping agents by id? I was looking at the [VMAS football scenario](https://github.com/proroklab/VectorizedMultiAgentSimulator/blob/main/vmas/scenarios/football.py) and tried to get some clue on how to set up policy mapping, but I couldn't figure out how the policies and agents are being mapped besides separating the agents in the blue and red team.

Any insights will be great!

Once again, thank you for your work! Cheers!

**Comment by matteobettini** [comment]
Hello,

Thanks for the feedback.

So this is a great question, I have never tried to use a dict instead of a tuple for the space. I will look into it and maybe make it possible to specify if you want tuples or dicts when creating an environment.

Just to clarify some doubts for you:
- vmas does not do any policy mapping and never deals with policies. it only provides a tuple of observations (one per agent) and takes a tuple of actions (one per agent)
- vmas in rllib is not a MultiAgentEnv. This is because vmas is vectorized and thus has to be a VectorEnv. MultiAgentEnvs which are vectorized are not supported in rllib yet https://github.com/ray-project/ray/pull/22768.
-  therefore , when i train vmas in rllib (in this repo) i consider it like a single agent VectorEnv and then use our custom trainer to train the multiple policies https://github.com/proroklab/rllib_differentiable_comms

**Comment by matteobettini** [comment]
Hey,

No problem.

Sorry, but I cannot help you implement this.
You will understand that we are very busy with our research and we cannot help with all use cases.

It seems it is not going to be too difficult, you will just have to figure out how to pipe the dictinary observations which are given as input to your model to different neural networks, or something similar.

**Comment by heng2j** [comment]
Hi @matteobettini yup, totally understood. And it was not a request for implementation, and just seeking for recommendations on how to use GPPO in this use case. Thank you and all the best for your research. 

And your works are significantly contributing to what we are doing. So thanks a ton for your contributions to the community!

**Comment by matteobettini** [comment]
Thanks.

Rllib is not really nice for multi-agent, and I am trying to move away from it.

I hope to provide some examples for training multi-agent vmas envs in torchrl https://github.com/pytorch/rl so.

So look out for those, they might be helpful

**Comment by heng2j** [comment]
Thank you @matteobettini  for the recommendation!
